export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_LOADING = 'GET_TOKEN_LOADING';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const CHANGE_SELECTED_SECTION = 'CHANGE_SELECTED_SECTION';